export const FIREBASE_API_KEY = process.env.EXPO_PUBLIC_FIREBASE_API_KEY;
export const FIREBASE_AUTH_DOMAIN =
  process.env.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN;
export const FIREBASE_PROJECT_ID = process.env.EXPO_PUBLIC_FIREBASE_PROJECT_ID;
export const FIREBASE_STORAGE_BUCKET =
  process.env.EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET;
export const FIREBASE_MESSAGING_SENDER_ID =
  process.env.EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID;
export const FIREBASE_APP_ID = process.env.EXPO_PUBLIC_FIREBASE_APP_ID;
export const FIREBASE_MEASUREMENT_ID =
  process.env.EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID;

export const BROADCAST_KEY = process.env.EXPO_PUBLIC_BROADCAST_KEY;
export const BROADCAST_CLUSTER = process.env.EXPO_PUBLIC_BROADCAST_CLUSTER;
export const BROADCAST_HOST = process.env.EXPO_PUBLIC_BROADCAST_HOST;
export const BROADCAST_PORT = Number(process.env.EXPO_PUBLIC_BROADCAST_PORT);
export const BROADCAST_SECURE =
  process.env.EXPO_PUBLIC_BROADCAST_SECURE === "true";

export const DIRECTIONAL_MAPS_API_KEY =
  process.env.EXPO_PUBLIC_DIRECTIONAL_MAPS_API_KEY || "";
